name: Python Application Test Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # If your UI tests require a specific web browser and webdriver, install them
    - name: Set up Chrome browser for Selenium tests
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
        echo "CHROMEWEBDRIVER=$(which chromedriver)" >> $GITHUB_ENV
        echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

    # Run your test script
    - name: Run tests
      run: |
        python report_unit.py

    # Optionally, upload test reports as artifacts
    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Reports
        path: path/to/your/test-reports/
